# formatter/summary_formatter.py

from datetime import datetime
from pathlib import Path
from agent.state import AgentState, FlagSeverity, FlagType
from agent.memory import AgentMemory, REQUIRED_FIELDS
from rich.console import Console

console = Console()


def _severity_emoji(severity: FlagSeverity) -> str:
    return {
        FlagSeverity.HIGH: "🚨",
        FlagSeverity.MEDIUM: "⚠️",
        FlagSeverity.LOW: "ℹ️",
    }.get(severity, "•")


def _flag_type_label(flag_type: FlagType) -> str:
    return {
        FlagType.CONFLICT: "CONFLICT",
        FlagType.MISSING: "MISSING",
        FlagType.PENDING: "PENDING RESULT",
        FlagType.MEDICATION_CHANGE: "MEDICATION CHANGE",
        FlagType.DRUG_INTERACTION: "DRUG INTERACTION",
        FlagType.UNRESOLVED: "LOW CONFIDENCE",
    }.get(flag_type, flag_type.value)


def build_discharge_summary(state: AgentState) -> str:
    """
    Build the structured discharge summary markdown.
    Uses AgentMemory to get display values — never accesses
    state.facts directly.
    """
    memory = AgentMemory(state)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = []

    # ── Header / Draft Banner ─────────────────────────────────────────
    lines.append("# DISCHARGE SUMMARY DRAFT")
    lines.append("")
    lines.append("> ⚠️ **THIS IS A DRAFT FOR CLINICIAN REVIEW ONLY**")
    lines.append(
        "> This document was generated by an AI agent and has NOT been "
        "verified or finalized."
    )
    lines.append(
        "> Every field marked [MISSING] or ⚠️ CONFLICT requires "
        "clinician attention before this document can be used clinically."
    )
    lines.append(
        "> All sourced values include document reference. "
        "Clinician should verify against original source documents."
    )
    lines.append("")
    lines.append(f"**Generated:** {now}")
    lines.append(f"**Patient ID:** {state.patient_id}")
    lines.append(f"**Agent Steps Used:** {state.steps}")
    if state.step_cap_reached:
        lines.append(
            "**⚠️ NOTE:** Agent reached step cap — "
            "some fields may be incomplete."
        )
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Clinical Flags Summary ────────────────────────────────────────
    if state.flags:
        lines.append("## 🚨 CLINICAL FLAGS — REQUIRES CLINICIAN ATTENTION")
        lines.append("")
        lines.append(
            f"**Total flags: {len(state.flags)}** "
            f"({len([f for f in state.flags if f.severity == FlagSeverity.HIGH])} HIGH, "
            f"{len([f for f in state.flags if f.severity == FlagSeverity.MEDIUM])} MEDIUM, "
            f"{len([f for f in state.flags if f.severity == FlagSeverity.LOW])} LOW)"
        )
        lines.append("")

        # Group by severity — HIGH first
        for severity in [FlagSeverity.HIGH, FlagSeverity.MEDIUM, FlagSeverity.LOW]:
            severity_flags = [
                f for f in state.flags if f.severity == severity
            ]
            if not severity_flags:
                continue

            emoji = _severity_emoji(severity)
            lines.append(f"### {emoji} {severity.value} Severity")
            lines.append("")

            for flag in severity_flags:
                lines.append(
                    f"- **[{_flag_type_label(flag.flag_type)}]** "
                    f"Field: `{flag.field}`"
                )
                lines.append(f"  {flag.description}")
                if flag.sources:
                    lines.append(
                        f"  *Sources: {', '.join(flag.sources)}*"
                    )
                lines.append("")

        lines.append("---")
        lines.append("")

    # ── Patient Demographics ──────────────────────────────────────────
    lines.append("## Patient Information")
    lines.append("")
    lines.append(
        f"**Demographics:** "
        f"{memory.get_best_value_for_output('patient_demographics')}"
    )
    lines.append(
        f"**Admission Date:** "
        f"{memory.get_best_value_for_output('admission_date')}"
    )
    lines.append(
        f"**Discharge Date:** "
        f"{memory.get_best_value_for_output('discharge_date')}"
    )
    lines.append(
        f"**Allergies:** "
        f"{memory.get_best_value_for_output('allergies')}"
    )
    lines.append(
        f"**Condition at Discharge:** "
        f"{memory.get_best_value_for_output('discharge_condition')}"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Diagnoses ─────────────────────────────────────────────────────
    lines.append("## Diagnoses")
    lines.append("")
    lines.append("### Principal Diagnosis")
    lines.append(memory.get_best_value_for_output("principal_diagnosis"))
    lines.append("")
    lines.append("### Secondary Diagnoses / Comorbidities")
    lines.append(memory.get_best_value_for_output("secondary_diagnoses"))
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Hospital Course ───────────────────────────────────────────────
    lines.append("## Hospital Course")
    lines.append("")
    lines.append(memory.get_best_value_for_output("hospital_course"))
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Procedures ────────────────────────────────────────────────────
    lines.append("## Procedures Performed")
    lines.append("")
    procs = memory.get_best_value_for_output("procedures_performed")
    # Format as bullet list if semicolon-separated
    if ";" in procs and not procs.startswith("⚠️") and not procs.startswith("["):
        for proc in procs.split(";"):
            proc = proc.strip()
            if proc:
                lines.append(f"- {proc}")
    else:
        lines.append(procs)
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Medications ───────────────────────────────────────────────────
    lines.append("## Medications")
    lines.append("")

    lines.append("### Admission Medications")
    lines.append("")
    if state.medications_admission:
        for med in state.medications_admission:
            dose_str = f" — {med.dose}" if med.dose else ""
            freq_str = f", {med.frequency}" if med.frequency else ""
            lines.append(f"- {med.name}{dose_str}{freq_str}")
    else:
        adm_fact = memory.get_best_value_for_output("admission_medications")
        lines.append(adm_fact)
    lines.append("")

    lines.append("### Discharge Medications")
    lines.append("")
    if state.medications_discharge:
        for med in state.medications_discharge:
            dose_str = f" — {med.dose}" if med.dose else ""
            freq_str = f", {med.frequency}" if med.frequency else ""
            lines.append(f"- {med.name}{dose_str}{freq_str}")
    else:
        dis_fact = memory.get_best_value_for_output("discharge_medications")
        lines.append(dis_fact)
    lines.append("")

    lines.append("### Medication Changes (Reconciliation)")
    lines.append("")

    # Collect medication change flags
    med_change_flags = [
        f for f in state.flags
        if f.flag_type == FlagType.MEDICATION_CHANGE
    ]

    if med_change_flags:
        lines.append(
            "⚠️ The following medication changes require clinician verification:"
        )
        lines.append("")
        for flag in med_change_flags:
            lines.append(f"- {flag.description}")
    else:
        lines.append(
            "No medication changes detected between admission "
            "and discharge."
        )
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Pending Results ───────────────────────────────────────────────
    lines.append("## Pending Results")
    lines.append("")
    if state.pending_items:
        lines.append(
            "⚠️ The following results were pending at time of discharge:"
        )
        lines.append("")
        for item in state.pending_items:
            lines.append(f"- {item}")
    else:
        pending_val = memory.get_best_value_for_output("pending_results")
        if pending_val.startswith("[MISSING"):
            lines.append("No results documented as pending.")
        else:
            lines.append(pending_val)
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Follow-up Instructions ────────────────────────────────────────
    lines.append("## Follow-up Instructions")
    lines.append("")
    followup = memory.get_best_value_for_output("follow_up_instructions")
    if ";" in followup and not followup.startswith("⚠️") and not followup.startswith("["):
        for instruction in followup.split(";"):
            instruction = instruction.strip()
            if instruction:
                lines.append(f"- {instruction}")
    else:
        lines.append(followup)
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Missing Fields Summary ────────────────────────────────────────
    if state.missing_fields:
        lines.append("## Fields Not Found in Source Documents")
        lines.append("")
        lines.append(
            "The following required fields could not be located "
            "in any source document. Clinician must supply:"
        )
        lines.append("")
        for field in state.missing_fields:
            lines.append(f"- `{field}`")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Drug Interactions ─────────────────────────────────────────────
    drug_flags = [
        f for f in state.flags
        if f.flag_type == FlagType.DRUG_INTERACTION
    ]
    if drug_flags:
        lines.append("## Drug Interaction Alerts")
        lines.append("")
        for flag in drug_flags:
            lines.append(f"- ⚠️ {flag.description}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────
    lines.append("")
    lines.append(
        "*This discharge summary draft was generated by an AI agent. "
        "It must be reviewed, verified, and countersigned by a licensed "
        "clinician before use in any clinical context. "
        "The AI agent does not make clinical decisions.*"
    )

    return "\n".join(lines)


def build_agent_trace(state: AgentState) -> str:
    """
    Build the agent trace log as readable markdown.
    Shows every step: reasoning, action, inputs, result, next decision.
    """
    lines = []

    lines.append("# Agent Trace Log")
    lines.append("")
    lines.append(f"**Patient ID:** {state.patient_id}")
    lines.append(f"**Total Steps:** {state.steps}")
    lines.append(
        f"**Completed Normally:** "
        f"{'No — step cap reached' if state.step_cap_reached else 'Yes'}"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    if not state.trace:
        lines.append("*No trace entries recorded.*")
        return "\n".join(lines)

    for entry in state.trace:
        step_num = entry.get("step", "?")
        lines.append(f"## Step {step_num}")
        lines.append("")

        lines.append(f"**Reasoning:** {entry.get('reasoning', 'N/A')}")
        lines.append("")

        lines.append(f"**Action:** `{entry.get('action', 'N/A')}`")
        lines.append("")

        inputs = entry.get("inputs", {})
        if inputs:
            lines.append("**Inputs:**")
            for k, v in inputs.items():
                lines.append(f"  - `{k}`: {v}")
            lines.append("")

        lines.append(f"**Result:** {entry.get('result', 'N/A')}")
        lines.append("")

        lines.append(
            f"**Next Decision:** {entry.get('next_decision', 'N/A')}"
        )
        lines.append("")
        lines.append("---")
        lines.append("")

    # Summary at the end
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Fields extracted: {len(state.extracted_fields)}")
    lines.append(f"- Fields missing: {len(state.missing_fields)}")
    lines.append(f"- Pending items: {len(state.pending_items)}")
    lines.append(f"- Clinical flags raised: {len(state.flags)}")
    lines.append(
        f"- High severity flags: "
        f"{len([f for f in state.flags if f.severity == FlagSeverity.HIGH])}"
    )

    return "\n".join(lines)


def save_outputs(state: AgentState, output_dir: str = "outputs") -> dict:
    """
    Generate both output files and save them to disk.
    Returns paths of saved files.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    summary_path = output_path / "discharge_summary.md"
    trace_path = output_path / "agent_trace.md"

    console.print("\n[bold cyan]Generating output files...[/bold cyan]")

    # Build and save discharge summary
    summary_content = build_discharge_summary(state)
    summary_path.write_text(summary_content, encoding="utf-8")
    console.print(f"[green]✓ Discharge summary saved:[/green] {summary_path}")

    # Build and save trace
    trace_content = build_agent_trace(state)
    trace_path.write_text(trace_content, encoding="utf-8")
    console.print(f"[green]✓ Agent trace saved:[/green] {trace_path}")

    return {
        "summary_path": str(summary_path),
        "trace_path": str(trace_path)
    }